# Generated by Django 5.2.8 on 2025-11-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
