# Generated by Django 5.2.8 on 2025-11-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_secondary',
            field=models.ImageField(blank=True, null=True, upload_to='item_images'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_tertiary',
            field=models.ImageField(blank=True, null=True, upload_to='item_images'),
        ),
    ]
