# Generated by Django 5.2.8 on 2025-11-17 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0004_item_image_secondary_item_image_tertiary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("item", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="comments", to="item.item")),
                ("created_by", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="item_comments", to=settings.AUTH_USER_MODEL)),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name="replies", to="item.comment")),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="DiscussionSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("agenda", models.TextField(blank=True)),
                ("scheduled_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="discussion_schedules", to=settings.AUTH_USER_MODEL)),
                ("item", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="discussion_schedules", to="item.item")),
            ],
            options={
                "ordering": ("scheduled_at",),
            },
        ),
    ]
