# Generated by Django 5.2.8 on 2025-11-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0005_item_image_secondary_item_image_tertiary"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussionschedule",
            name="location_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="discussionschedule",
            name="location_url",
            field=models.URLField(blank=True),
        ),
    ]
