# Generated by Django 5.2.8 on 2026-04-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perpustakaan',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='perpustakaan',
            name='social_media',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
